# Generated by Django 5.0.4 on 2025-04-24 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Damaged_system')),
            ],
            options={
                'verbose_name': 'DamagedSystem',
                'verbose_name_plural': 'DamagedSystems',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='createtime')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altscore.damagedsystem')),
            ],
            options={
                'verbose_name': 'RequestLog',
                'verbose_name_plural': 'RequestLogs',
            },
        ),
        migrations.CreateModel(
            name='SystemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='altscore.damagedsystem', verbose_name='System')),
            ],
            options={
                'verbose_name': 'SystemCode',
                'verbose_name_plural': 'SystemCodes',
            },
        ),
    ]
