# Generated by Django 5.1.6 on 2025-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('pages_number', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(1, 'Horror'), (2, 'Romance'), (3, 'Science fiction'), (4, 'Fantasy')])),
                ('status', models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updatetime', 'author'],
            },
        ),
    ]
