# Generated by Django 5.1.6 on 2025-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full name')),
                ('local_id', models.CharField(max_length=50, verbose_name='Local ID')),
                ('income', models.FloatField(verbose_name='Monthly income')),
            ],
        ),
    ]
